public class prueba
{
	String var1, var2="hola";
	int var3, []var4;
	double var3;
	if (var3<var4)
	{
		System.out.println("la var4 es mayor que la var3");
	}
	else
	{
		System.out.println("la var3 es mayor que la var4");
	}
	while(var3>var4)
	{
		System.out.println("que mas pues");
	}
	switch(var2)
	{
		case 1:
			var1="oe";
		break;
		default:
			System.out.println("no haga nada");
	}
	for(int k=1;k=10;k++)
	{
		var3 = var3 + 2;
	}
}
